markdown: rdiscount
pygments: true
permalink: /:title
auto: true
rdiscount:
  extensions: [smart]

name: Thoughts and Patterns of a Developer
url: http://thoughts.silentworks.co.uk
description: A developers blog about development thoughts and patterns.
twitter: silentworks
github: silentworks