markdown: kramdown
rouge: true
permalink: /:title
auto: true

name: Thoughts and Patterns of a Developer
url: http://thoughts.silentworks.co.uk
description: A developers blog about development thoughts and patterns.
twitter: silentworks
github: silentworks
gravatar_url: http://gravatar.com/avatar/1d7fd497a94d51095369d3ea91f7138a
